# -*- mode: ruby -*-
# vi: set ft=ruby :

###
# Copyright 2018 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

# This Vagrantfile assumes an all-in-one setup
Vagrant.configure(2) do |config|

  config.vm.define "infosvr" do |infosvr|
    infosvr.vm.box = "centos/7"
    infosvr.vm.network "private_network", ip: "192.168.27.12"
    infosvr.vm.hostname = "infosvr.vagrant.ibm.com"
    infosvr.vm.synced_folder ".", "/vagrant", disabled: true
    infosvr.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 8192
      vb.cpus = 2
    end
  end

end
